version: '3.8'

services:
  kobounty:
    image: node:18
    container_name: kobounty_app
    working_dir: /src
    volumes:
      - .:/src
      - /src/node_modules
    ports:
      - "9000:9000" # Adjust this if needed
    environment:
      - NODE_ENV=development
    command: ["sh", "-c", "npm install && npm run dev"]
    restart: unless-stopped
